services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: inventory_control_system
      POSTGRES_USER: inventory_control_system
      POSTGRES_PASSWORD: 123